# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

    ignore:
      - dependency-name: "@sanity/client"
      - dependency-name: "@sanity/code-input"
      - dependency-name: "@sanity/eslint-config-studio"
      - dependency-name: "@sanity/icons"
      - dependency-name: "@sanity/vision"
      - dependency-name: "@tailwindcss/postcss"
      - dependency-name: "@testing-library/dom"
      - dependency-name: "@testing-library/jest-dom"
      - dependency-name: "@testing-library/react"
      - dependency-name: "@trivago/prettier-plugin-sort-imports"
      - dependency-name: "@types/jest"
      - dependency-name: "@types/node"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
      - dependency-name: "eslint"
      - dependency-name: "eslint-config-next"
      - dependency-name: "eslint-config-prettier"
      - dependency-name: "jest"
      - dependency-name: "jest-environment-jsdom"
      - dependency-name: "nx"
      - dependency-name: "prettier"
      - dependency-name: "prettier-plugin-tailwindcss"
      - dependency-name: "sort-package-json"
      - dependency-name: "studio"
      - dependency-name: "tailwindcss"
      - dependency-name: "ts-node"
      - dependency-name: "tw-animate-css"
      - dependency-name: "typescript"

    groups:
      react-stack:
        patterns:
          - "react"
          - "react-dom"

      next-stack:
        patterns:
          - "next"
          - "eslint-config-next"
